# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/21pa1a0487@vishnu.edu.in/ml")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM ml.data.scada_failure_base"))

# COMMAND ----------

# MAGIC %sql
# MAGIC DESCRIBE TABLE ml.data.bronze_scada_raw;

# COMMAND ----------

# Display schema
df = spark.table("ml.data.scada_failure_base")
df.printSchema()

# Show summary statistics
display(df.describe())

# Show null counts per column
from pyspark.sql.functions import col, sum as spark_sum
null_counts = df.select([spark_sum(col(c).isNull().cast("int")).alias(c) for c in df.columns])
display(null_counts)

# Show value counts for categorical columns (replace 'status' with actual categorical column names)
categorical_cols = [field.name for field in df.schema.fields if field.dataType.simpleString() == 'string']
for col_name in categorical_cols:
    display(df.groupBy(col_name).count().orderBy("count", ascending=False))

# Show correlation for numeric columns
numeric_cols = [field.name for field in df.schema.fields if field.dataType.simpleString() in ['int', 'double', 'float', 'long']]
if len(numeric_cols) >= 2:
    for i in range(len(numeric_cols)):
        for j in range(i+1, len(numeric_cols)):
            corr = df.stat.corr(numeric_cols[i], numeric_cols[j])
            print(f"Correlation between {numeric_cols[i]} and {numeric_cols[j]}: {corr}")

# Visualize distributions for numeric columns
for col_name in numeric_cols:
    display(df.select(col_name))

# COMMAND ----------

# Plot scatter to show relation between power_kw_avg and wind_speed_m_s_avg
display(df.toPandas().plot.scatter(x='wind_speed_m_s_avg', y='power_kw_avg'))

# COMMAND ----------

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Compute correlation matrix for numeric columns
corr = df.select(numeric_cols).toPandas().corr()

# Generate a mask for the upper triangle
mask = np.triu(np.ones_like(corr, dtype=bool))

# Set up the matplotlib figure
plt.figure(figsize=(10, 8))

# Draw the heatmap
sns.heatmap(corr, mask=mask, cmap="coolwarm", vmax=1.0, vmin=-1.0, center=0,
            square=True, linewidths=0.5, annot=True, fmt=".2f")

plt.title("Feature Correlation Matrix")
plt.tight_layout()
display(plt.gcf())
plt.close()
